### ISSUE TITLE
How to inscrease titlebar buttons size?

### ISSUE THREAD

**Issue by SubatomicCat** [yeyushengfan258/Reversal-gtk-theme#1]
How can I increase the size of the titlebar buttons? I would like them to be 2px larger in diameter, but I haven't figured out what controls the size of the spheres...
I don't mind making the edits directly to the CSS file.

I believe this is the code that governs that. But increasing the min values did nothing, same as playing with other values for padding and margin.

``` css
/*********************
 * GtkWindowControls *
 *********************/
windowcontrols > button {
  min-height: 16px;
  min-width: 16px;
  padding: 9px 0;
  margin-left: 4px;
  margin-right: 4px;
  box-shadow: none;
}

windowcontrols > button.minimize, windowcontrols > button.maximize, windowcontrols > button.close {
  color: transparent;
  background: none;
}

windowcontrols > button.minimize:hover, windowcontrols > button.minimize:active, windowcontrols > button.maximize:hover, windowcontrols > button.maximize:active, windowcontrols > button.close:hover, windowcontrols > button.close:active {
  box-shadow: none;
}

windowcontrols > button.minimize:hover, windowcontrols > button.minimize:active, windowcontrols > button.maximize:hover, windowcontrols > button.maximize:active, windowcontrols > button.close:hover, windowcontrols > button.close:active {
  color: white;
}

windowcontrols > button.minimize:backdrop > image, windowcontrols > button.maximize:backdrop > image, windowcontrols > button.close:backdrop > image {
  background-color: alpha(@headerbar_fg_color,0.3);
}

windowcontrols > button.minimize:backdrop:hover, windowcontrols > button.minimize:backdrop:active, windowcontrols > button.maximize:backdrop:hover, windowcontrols > button.maximize:backdrop:active, windowcontrols > button.close:backdrop:hover, windowcontrols > button.close:backdrop:active {
  color: alpha(@headerbar_fg_color,0.45);
}

windowcontrols > button.minimize > image {
  background-color: #ffcc00;
}

windowcontrols > button.minimize:active > image {
  background-color: mix(black,#ffcc00,0.75);
}

windowcontrols > button.maximize > image {
  background-color: #00c19f;
}

windowcontrols > button.maximize:active > image {
  background-color: mix(black,#00c19f,0.75);
}

windowcontrols > button.close > image {
  background-color: #ff4e5e;
}

windowcontrols > button.close:active > image {
  background-color: mix(black,#ff4e5e,0.75);
}

windowcontrols {
  border-spacing: 6px;
}

windowcontrols:not(.empty).start:dir(ltr), windowcontrols:not(.empty).end:dir(rtl) {
  margin-right: 6px;
  margin-left: 6px;
}

windowcontrols:not(.empty).start:dir(rtl), windowcontrols:not(.empty).end:dir(ltr) {
  margin-left: 6px;
  margin-right: 6px;
}

windowcontrols > button > image {
  padding: 0;
  border-radius: 100%;
  transition: background 200ms cubic-bezier(0.25, 0.46, 0.45, 0.94), box-shadow 200ms cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

windowcontrols > .icon {
  margin: 9px;
}
```
